### ISSUE TITLE
Stackage nightly build failure

### ISSUE THREAD

**Issue by decentral1se** [nakaji-dayo/yesod-job-queue#12]
```
Preprocessing library yesod-job-queue-0.3.0.2...
[1 of 5] Compiling Yesod.JobQueue.Types ( Yesod/JobQueue/Types.hs, dist/build/Yesod/JobQueue/Types.o )
[2 of 5] Compiling Yesod.JobQueue.Routes ( Yesod/JobQueue/Routes.hs, dist/build/Yesod/JobQueue/Routes.o )
[3 of 5] Compiling Yesod.JobQueue.GenericConstr ( Yesod/JobQueue/GenericConstr.hs, dist/build/Yesod/JobQueue/GenericConstr.o )
[4 of 5] Compiling Yesod.JobQueue   ( Yesod/JobQueue.hs, dist/build/Yesod/JobQueue.o )

Yesod/JobQueue.hs:72:10: error:
    Duplicate instance declarations:
      instance ToJSON U.UUID -- Defined at Yesod/JobQueue.hs:72:10
      instance ToJSON U.UUID
        -- Defined in <E2><80><98>aeson-1.1.2.0:Data.Aeson.Types.ToJSON<E2><80><99>
```

**Comment by bergmark** [comment]
@lwm Did you try adding an `yesod-job-queue < 0.3.0.2` bound? It's a new release so we should try to stick with the old version.

The issue is still valid though :)

**Comment by decentral1se** [comment]
@bergmark,  I was thinking of it but I thought that https://github.com/nakaji-dayo/yesod-job-queue/issues/10 might happen then and just disabled. 

Can put in a 0.3.0.1 bound if needed!

**Comment by nakaji-dayo** [comment]
@lwm Thanks for creating issue.
I fixed it in https://github.com/nakaji-dayo/yesod-job-queue/pull/13/commits/3072e5f0f91eb7e1d0392e04e7a421d3dddef486 .
And, released it as 0.3.0.4 .

**Comment by nakaji-dayo** [comment]
@lwm @bergmark Thanks,
Yes, old version has problem #10 . So it is disabled.

**Comment by decentral1se** [comment]
@nakaji-dayo, thanks! I'll close this then in favour of https://github.com/fpco/stackage/pull/2521.
