### ISSUE TITLE
Error on app js run

### ISSUE THREAD

**Issue by amitaibu** [nakaji-dayo/yesod-job-queue#3]
It's not written in the README how to invoke the app, but from a quick look it seems `npm run bs` is the right step. However I now get:

![localhost_3001](https://cloud.githubusercontent.com/assets/125707/14883276/04cabbd0-0d46-11e6-996c-c9de254ca6a0.jpg)

What am I missing?

(btw, cyclejs is great but I prefer [Elm](http://elm-lang.org/) 😉 )

**Comment by nakaji-dayo** [comment]
I'm sorry, `npm run bs` is currently imcomplete.

Usually, you can access `app`  from  `/manager` in the subsite.
(If you are running example: `http://localhost:3000/job/manager`)

However, in development of the app,
It takes long time to build the package each time `app.bundle.js` is changed.
So, I'm using `npm run bs` to serve `app.bundle.js`, and change `app.bundle.js` path in `example/Main.hs`.

```
jobManagerJSUrl _ = "http://localhost:3001/dist/app.bundle.js
```

umm, I think this is not good way.

---

Yeah, I'm interested in "Elm" and [PureScript](http://www.purescript.org/).
I might rewrite this with any alt js 👍. 
but, I can’t decide what to use yet.

Thanks!

**Comment by amitaibu** [comment]
👍  - however now when I open the URL I get:

![yesodjobqueue_manager](https://cloud.githubusercontent.com/assets/125707/14961395/e86d3c06-10a1-11e6-96be-1912093b0f09.jpg)

I suspect it's because I don't have Redis running. Are you using a Docker container to run Redis and somehow connect it to your Yesod app?

**Comment by nakaji-dayo** [comment]
I also think it's cause, although I can't conclude without server side log.

No, I'm not using Docker. Would you need Docker?
This library only uses Redis.

**Comment by nakaji-dayo** [comment]
I did commit related.

"allow to change connection info for redis" https://github.com/nakaji-dayo/yesod-job-queue/commit/380b0b3a563ce8574e199cbd89400713baafc110

**Comment by amitaibu** [comment]
I'll check it and report - thanks.

**Comment by amitaibu** [comment]
Yes, after I did a `brew install redis` it works fine. Now I can start learning from your library ;)

![yesodjobqueue_manager](https://cloud.githubusercontent.com/assets/125707/15024066/ea4885b2-123b-11e6-8518-a0f6b599a05e.jpg)

**Comment by nakaji-dayo** [comment]
Thanks for report !
