### ISSUE TITLE
Documentation for running queues

### ISSUE THREAD

**Issue by danpalmer** [nakaji-dayo/yesod-job-queue#9]
As far as I can tell from the source, `startDequeue` and `startJobScheduler` must be run to process items from the queue. Could this be added to the documentation?

I would imagine that a separate binary with a separate main method would be the best way to go, to separate the running of the site from the queue processing. That should be fairly easy to set up in cabal, but an example in the docs would be great.

**Comment by cdepillabout** [comment]
@danpalmer You're totally right.  There is a small example in [`example/Main.hs`](https://github.com/nakaji-dayo/yesod-job-queue/blob/master/example/Main.hs), but that information should also be added to the README and the haddocks.

Could you edit the README to add this information and send a PR?

**Comment by danpalmer** [comment]
Oh ok, I've re-read and I think I was mistaken the first time. I saw the last part of `main` being `warp 3000 app`, and assumed that the intention was that queue processing would happen in the web workers, but I'm guessing that it is in fact just intended that the queue monitoring interface is used from the queue processors, is that correct? Can the warp server be omitted entirely?

Essentially, I'd like to be able to run `n` web servers that can all enqueue tasks, and `m` queue processors that will take tasks off the queue, and have those be completely separate processes probably on separate machines. In a perfect environment I'd probably run the management interface as another separate single web server. Does that all sound reasonable?

**Comment by cdepillabout** [comment]
> I saw the last part of main being warp 3000 app, and assumed that the intention was that queue processing would happen in the web workers

You're right, this is how the `example.hs` works.

> I'm guessing that it is in fact just intended that the queue monitoring interface is used from the queue processors, is that correct? Can the warp server be omitted entirely? Essentially, I'd like to be able to run n web servers that can all enqueue tasks, and m queue processors that will take tasks off the queue, and have those be completely separate processes probably on separate machines.

I'm pretty sure this will work. [`enqueue`](https://github.com/nakaji-dayo/yesod-job-queue/blob/master/Yesod/JobQueue.hs#L178) is really just [`rpush`ing](http://redis.io/commands/RPUSH) an item onto a redis list.  The queue processor is just [`blpop`ing](http://redis.io/commands/BLPOP) an item from that list.

To be honest, I'm not super familiar with redis, but I believe there will be no problem with running `n` web servers and `m` queue processors.  You just need to make sure that all the web servers and all the queue processors can access access redis.

> In a perfect environment I'd probably run the management interface as another separate single web server.

I'm not sure if this will work with the code as-is.  It looks like the jobs currently being run are kept track of in a `TVar` ([see here](https://github.com/nakaji-dayo/yesod-job-queue/blob/master/Yesod/JobQueue.hs#L172)).  I belive the management interface uses this information.

Maybe @nakaji-dayo could comment on whether this would be possible to change or work around?


Also, if you're planning on using `yesod-job-queue` in production, you should be aware that error handling is partially [not-implemented](https://github.com/nakaji-dayo/yesod-job-queue/blob/master/Yesod/JobQueue.hs#L152).  However, I imagine @nakaji-dayo would probably welcome a PR implementing some sort of error handling.

**Comment by nakaji-dayo** [comment]
Thanks @danpalmer and @cdepillabout.

> As far as I can tell from the source, startDequeue and startJobScheduler must be run to process items from the queue. Could this be added to the documentation?　

Yes, `startDequeue` is needed to execute the task from the queue.
`startJobScheduler` is needed when enqueue a job on schedule (like cron).

> Can the warp server be omitted entirely?

Yes, if you don't need a management interface and Web API, you should be able omit warp server.

> Essentially, I'd like to be able to run n web servers that can all enqueue tasks, and m queue processors that will take tasks off the queue, and have those be completely separate processes probably on separate machines. In a perfect environment I'd probably run the management interface as another separate single web server. Does that all sound reasonable? 

Yes, I think it is correct architecture.

I am the same idea as @cdepillabout.
Web servers and processing servers should work correctly.
However, I have not yet tried this.
In addition, you can not view the status of all processing servers in single management interface.

> I'm not sure if this will work with the code as-is. It looks like the jobs currently being run are kept track of in a TVar (see here). I belive the management interface uses this information.

Yes, the management interface refers to this TVar via [the web API](https://github.com/nakaji-dayo/yesod-job-queue/blob/master/Yesod/JobQueue.hs#L251).

> Maybe @nakaji-dayo could comment on whether this would be possible to change or work around?

Changes are required to monitor multiple servers via the management interface.

Several designs are conceivable, but I think the following method is the easiest:
-  Create a list of processing servers(dequeueing servers). or processing servers regist self information to Redis.
- The management interface server inquires each server about running jobs.

What do you think?

> However, I imagine @nakaji-dayo would probably welcome a PR implementing some sort of error handling.

Yes, I very welcome a PR implementing some sort of error handling.

**Comment by nakaji-dayo** [comment]
![img_3700](https://cloud.githubusercontent.com/assets/1113464/20639107/be5541b6-b3fd-11e6-94a6-7304fdb5ce60.JPG)
